#!/usr/bin/env python3
"""Generate immutable Swift catalog files from the JSON source catalog."""

# English: JSON is the editable source; Swift is the runtime artifact.
# Español: JSON es la fuente editable y Swift es el artefacto de runtime.
# 中文：JSON 是可维护源数据，Swift 是运行时产物。

from __future__ import annotations

import argparse
import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
CATALOG_DIR = SCRIPT_DIR.parents[1] / "PooToolsSource/PToolsDevice/Resources/DeviceCatalog"
DEFAULT_OUTPUT_DIR = SCRIPT_DIR.parents[1] / "PooToolsSource/PToolsDevice/Generated"
FAMILY_NAMES = {
    "iphone": "PTiPhoneCatalogGenerated",
    "ipad": "PTiPadCatalogGenerated",
    "ipod": "PTiPodCatalogGenerated",
    "apple-tv": "PTAppleTVCatalogGenerated",
    "apple-watch": "PTAppleWatchCatalogGenerated",
    "mac": "PTMacCatalogGenerated",
    "homepod": "PTHomePodCatalogGenerated",
    "apple-vision": "PTAppleVisionCatalogGenerated",
}


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_catalog(catalog_dir: Path) -> tuple[str, dict[str, list[dict]]]:
    files = sorted(catalog_dir.glob("*.json"))
    if not files:
        raise SystemExit(f"no catalog files found in {catalog_dir}")
    version = None
    grouped: dict[str, list[dict]] = {}
    for path in files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        current_version = payload.get("catalogVersion")
        if not isinstance(current_version, str) or not current_version:
            raise SystemExit(f"missing catalogVersion: {path}")
        version = version or current_version
        if version != current_version:
            raise SystemExit(f"catalog version mismatch: {path}")
        grouped[path.stem] = payload.get("devices", [])
    assert version is not None
    return version, grouped


def traits_expression(device: dict) -> str:
    traits = device.get("traits", {})
    keys = (
        "hasSensorHousing",
        "hasRoundedDisplayCorners",
        "has3dTouchSupport",
        "supportsWirelessCharging",
        "hasLidarSensor",
        "isFaceIDCapable",
        "isTouchIDCapable",
    )
    arguments = [f"{key}: {str(bool(traits.get(key, False))).lower()}" for key in keys]
    if "ppi" in traits:
        arguments.append(f"ppi: {traits['ppi']}")
    return ".init(" + ", ".join(arguments) + ")"


def specification_expression(device: dict) -> str:
    identifiers = ", ".join(swift_string(value) for value in device["identifiers"])
    return (
        "PTDeviceSpecification("
        f"model: PTDeviceModel({swift_string(device['id'])}), "
        f"marketingName: {swift_string(device['marketingName'])}, "
        f"identifiers: [{identifiers}], "
        f"family: .{device['family']}, "
        f"platform: .{device['platform']}, "
        f"releaseYear: {device.get('releaseYear') if device.get('releaseYear') is not None else 'nil'}, "
        f"formFactor: .{device['formFactor']}, "
        f"processorFamily: {swift_string(device['processorFamily']) if device.get('processorFamily') else 'nil'}, "
        f"traits: {traits_expression(device)}"
        ")"
    )


def render_group(type_name: str, devices: list[dict]) -> str:
    lines = [
        "// AUTO-GENERATED FILE.",
        "// DO NOT EDIT.",
        "// Generated by Scripts/Device/generate_device_catalog.py.",
        "// English: Generated catalog data is immutable at runtime.",
        "// Español: Los datos generados del catálogo son inmutables en runtime.",
        "// 中文：生成的目录数据在运行时不可变。",
        "",
        "import Foundation",
        "",
        f"internal enum {type_name} {{",
        "    static let specifications: [PTDeviceSpecification] = [",
    ]
    lines.extend(f"        {specification_expression(device)}," for device in devices)
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def render_index(version: str, group_types: list[str]) -> str:
    lines = [
        "// AUTO-GENERATED FILE.",
        "// DO NOT EDIT.",
        "// Generated by Scripts/Device/generate_device_catalog.py.",
        "// English: This index combines per-platform generated catalogs.",
        "// Español: Este índice combina los catálogos generados por plataforma.",
        "// 中文：该索引合并各平台生成的目录。",
        "",
        "import Foundation",
        "",
        "internal enum PTDeviceCatalogGenerated {",
        f"    static let version = {swift_string(version)}",
        "    static let specifications: [PTDeviceSpecification] = [",
    ]
    for group_type in group_types:
        lines.append(f"        {group_type}.specifications,")
    lines.extend(["    ].flatMap { $0 }", "}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog-dir", type=Path, default=CATALOG_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    version, grouped = load_catalog(args.catalog_dir)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for old_file in args.output_dir.glob("*.generated.swift"):
        old_file.unlink()

    group_types = []
    for stem, type_name in FAMILY_NAMES.items():
        devices = grouped.get(stem, [])
        output_name = f"{type_name.removesuffix('Generated')}.generated.swift"
        (args.output_dir / output_name).write_text(render_group(type_name, devices), encoding="utf-8")
        group_types.append(type_name)
    (args.output_dir / "PTDeviceIdentifierIndex.generated.swift").write_text(
        render_index(version, group_types), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
