platform :ios, '8.0'
use_frameworks!

target 'PooTools_Example' do
  pod 'PooTools', :path => '../'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'SSZipArchive'
  pod "GCDWebServer/WebUploader", "~> 3.0"
#  target 'PooTools_Tests' do
#    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
#  end
end
