platform :ios, '10.0'
use_frameworks!

target 'PooTools_Example' do
  pod 'PooTools', :path => '../'
  pod 'WZLBadge'
  pod 'SnapKit'
  pod 'YYKit'
  pod 'SwifterSwift'
#  pod 'WoodPeckeriOS'
  pod "GCDWebServer/WebUploader", "~> 3.0"
  pod 'HandyJSON' #JSON处理
  pod 'DeviceKit', '~> 4.0'
end
