// English: PTSymbolGen is a maintainer tool, not a normal application build dependency.
// Español: PTSymbolGen es una herramienta de mantenimiento, no una dependencia del build normal.
// 中文：PTSymbolGen 是维护工具，不参与普通应用构建依赖。

import Foundation

private struct Catalog: Codable {
    let catalogVersion: String
    let symbols: [Entry]
}

private struct Entry: Codable {
    let name: String
    let swiftName: String
    let introducedIOS: String
    let deprecatedIOS: String?
    let renamedTo: String?
    let supportsVariableValue: Bool
}

private enum GeneratorError: Error, CustomStringConvertible {
    case usage
    case duplicateRawValue(String)
    case duplicateSwiftName(String)

    var description: String {
        switch self {
        case .usage:
            return "usage: PTSymbolGen generate <catalog.json> <output.swift> | diff <old.json> <new.json> <report.md>"
        case let .duplicateRawValue(value):
            return "duplicate symbol name: \(value)"
        case let .duplicateSwiftName(value):
            return "duplicate Swift identifier: \(value)"
        }
    }
}

private func load(_ path: String) throws -> Catalog {
    let data = try Data(contentsOf: URL(fileURLWithPath: path))
    let catalog = try JSONDecoder().decode(Catalog.self, from: data)
    let rawValues = catalog.symbols.map(\.name)
    let swiftNames = catalog.symbols.map(\.swiftName)
    if let duplicate = Dictionary(grouping: rawValues, by: { $0 }).first(where: { $0.value.count > 1 })?.key {
        throw GeneratorError.duplicateRawValue(duplicate)
    }
    if let duplicate = Dictionary(grouping: swiftNames, by: { $0 }).first(where: { $0.value.count > 1 })?.key {
        throw GeneratorError.duplicateSwiftName(duplicate)
    }
    return catalog
}

private func swiftLiteral(_ value: String) -> String {
    value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
}

private func generatedSwift(_ catalog: Catalog) -> String {
    let entries = catalog.symbols.sorted { $0.name < $1.name }
    var output = """
    // Generated by Tools/PTSymbolGen. Do not edit manually.
    // Generado por Tools/PTSymbolGen. No editar manualmente.
    // 由 Tools/PTSymbolGen 生成，请勿手工修改。

    public extension PTSymbol {

    """
    for entry in entries {
        if entry.introducedIOS != "17.0" {
            output += "    @available(iOS \(entry.introducedIOS), *)\n"
        }
        output += "    static let \(entry.swiftName) = PTSymbol(rawValue: \"\(swiftLiteral(entry.name))\")\n"
    }
    output += """
    }

    enum PTSymbolCatalogGenerated {
        static let allSymbols: [PTSymbolDescriptor] = [
    """
    for entry in entries {
        let deprecated = entry.deprecatedIOS.map { "\"\(swiftLiteral($0))\"" } ?? "nil"
        let renamed = entry.renamedTo.map { "PTSymbol(rawValue: \"\(swiftLiteral($0))\")" } ?? "nil"
        output += "        PTSymbolDescriptor(symbol: .\(entry.swiftName), swiftName: \"\(swiftLiteral(entry.swiftName))\", availability: PTSymbolAvailability(introducedIOS: \"\(swiftLiteral(entry.introducedIOS))\", deprecatedIOS: \(deprecated)), renamedTo: \(renamed), supportsVariableValue: \(entry.supportsVariableValue)),\n"
    }
    output += """
        ]
    }
    """
    return output
}

private func writeGenerated(catalogPath: String, outputPath: String) throws {
    let catalog = try load(catalogPath)
    try generatedSwift(catalog).write(to: URL(fileURLWithPath: outputPath), atomically: true, encoding: .utf8)
}

private func writeDiff(oldPath: String, newPath: String, outputPath: String) throws {
    let oldCatalog = try load(oldPath)
    let newCatalog = try load(newPath)
    let old = Set(oldCatalog.symbols.map(\.name))
    let new = Set(newCatalog.symbols.map(\.name))
    let added = new.subtracting(old).sorted()
    let removed = old.subtracting(new).sorted()
    var output = """
    # SF Symbol Catalog Diff

    - Catalog: `\(newCatalog.catalogVersion)`
    - Added: \(added.count)
    - Removed: \(removed.count)
    - Renamed: 0

    ## Added

    """
    output += added.map { "- `\($0)`" }.joined(separator: "\n")
    output += "\n\n## Removed\n\n"
    output += removed.map { "- `\($0)`" }.joined(separator: "\n")
    output += "\n"
    try output.write(to: URL(fileURLWithPath: outputPath), atomically: true, encoding: .utf8)
}

do {
    let arguments = Array(CommandLine.arguments.dropFirst())
    if arguments.count == 3, arguments[0] == "generate" {
        try writeGenerated(catalogPath: arguments[1], outputPath: arguments[2])
    }
    else if arguments.count == 4, arguments[0] == "diff" {
        try writeDiff(oldPath: arguments[1], newPath: arguments[2], outputPath: arguments[3])
    }
    else {
        throw GeneratorError.usage
    }
}
catch {
    fputs("PTSymbolGen: \(error)\n", stderr)
    exit(1)
}
