//
//  PTModelMacros.swift
//
// English: Lightweight Swift macros generate schema metadata while keeping codec behavior in PTModelCore.
// Español: Estas macros ligeras generan metadatos de esquema y mantienen el comportamiento del codec en PTModelCore.
// 中文：轻量 Swift 宏只生成 Schema 元数据，具体 codec 行为仍由 PTModelCore 负责。
//

import SwiftCompilerPlugin
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

enum PTMacroSourceBuilder {
    struct FieldInfo {
        let name: String
        let typeName: String
        let wireKey: String
        let path: String?
        let defaultExpression: String?
        let isMutable: Bool
        let required: Bool
        let flattened: Bool
        let lossy: Bool
        let stringified: Bool
        let annotations: [String]
        let encoding: String
        let missing: String
        let null: String
        let invalid: String
        let isObjCCompatible: Bool
    }

    static func typeName(from declaration: some DeclGroupSyntax) -> String? {
        if let declaration = declaration.as(StructDeclSyntax.self) {
            return declaration.name.text + genericArguments(declaration.genericParameterClause)
        }
        if let declaration = declaration.as(ClassDeclSyntax.self) {
            return declaration.name.text + genericArguments(declaration.genericParameterClause)
        }
        return nil
    }

    // English: Generated references use generic parameter names, not their declaration constraints.
    // Español: Las referencias generadas usan nombres de parámetros genéricos, no sus restricciones de declaración.
    // 中文：宏生成的类型引用只使用泛型参数名，不把声明约束重复带入类型引用。
    private static func genericArguments(_ clause: GenericParameterClauseSyntax?) -> String {
        guard let clause, !clause.parameters.isEmpty else { return "" }
        let names = clause.parameters.map { $0.name.text }.joined(separator: ", ")
        return "<\(names)>"
    }

    static func superclassName(from declaration: some DeclGroupSyntax) -> String? {
        guard let declaration = declaration.as(ClassDeclSyntax.self),
              let inherited = declaration.inheritanceClause?.inheritedTypes.first?.type.trimmedDescription,
              !["NSObject", "Codable", "Decodable", "Encodable", "Sendable"].contains(inherited) else {
            return nil
        }
        return inherited
    }

    static func hasDirectClassInitializer(_ declaration: some DeclGroupSyntax,
                                          fields: [FieldInfo]) -> Bool {
        guard let declaration = declaration.as(ClassDeclSyntax.self) else { return false }
        if declaration.memberBlock.members.contains(where: { member in
            guard let initializer = member.decl.as(InitializerDeclSyntax.self) else { return false }
            return initializer.signature.parameterClause.parameters.isEmpty
        }) {
            return true
        }
        return fields.allSatisfy { $0.defaultExpression != nil || $0.typeName.hasSuffix("?") }
    }

    // English: Observation storage is generated by another macro and cannot be discovered as stable PTModel fields.
    // Español: El almacenamiento de Observation lo genera otra macro y no puede descubrirse como campos PTModel estables.
    // 中文：Observation 存储由其他宏生成，不能被识别为稳定的 PTModel 字段。
    static func validateTypeBoundary(_ declaration: some DeclGroupSyntax) throws {
        let attributes = declaration.attributes.compactMap { element -> AttributeSyntax? in
            guard case .attribute(let attribute) = element else { return nil }
            return attribute
        }
        let names = attributes.map { $0.attributeName.trimmedDescription }
        if names.contains("Observable") {
            throw MacroExpansionErrorMessage("@PTModel does not synthesize Observation storage; use a manual PTStaticModel schema for @Observable types")
        }
    }

    static func fields(from declaration: some DeclGroupSyntax) throws -> [FieldInfo] {
        var result: [FieldInfo] = []
        let codingKeys = codingKeyMap(from: declaration)
        for member in declaration.memberBlock.members {
            guard let variable = member.decl.as(VariableDeclSyntax.self) else { continue }
            guard variable.bindings.count == 1,
                  let binding = variable.bindings.first,
                  let name = binding.pattern.as(IdentifierPatternSyntax.self)?.identifier.text else {
                throw MacroExpansionErrorMessage("@PTModel requires one named stored property per declaration")
            }
            let typeName = binding.typeAnnotation?.type.trimmedDescription
                ?? inferredTypeName(from: binding.initializer?.value)
            guard let typeName else {
                throw MacroExpansionErrorMessage("@PTModel requires an explicit type for properties without a supported literal initializer")
            }
            if let accessorBlock = binding.accessorBlock {
                let observerOnly: Bool
                switch accessorBlock.accessors {
                case .accessors(let accessors):
                    observerOnly = accessors.allSatisfy { accessor in
                        ["willSet", "didSet"].contains(accessor.accessorSpecifier.text)
                    }
                case .getter:
                    observerOnly = false
                }
                guard observerOnly else {
                    throw MacroExpansionErrorMessage("@PTModel only supports stored properties and willSet/didSet observers")
                }
            }
            let modifiers = Set(variable.modifiers.map(\.name.text))
            guard modifiers.isDisjoint(with: ["static", "class", "lazy", "weak", "unowned"]) else {
                throw MacroExpansionErrorMessage("@PTModel only supports stored instance properties")
            }
            let attributes = variable.attributes.compactMap { element -> AttributeSyntax? in
                guard case .attribute(let attribute) = element else { return nil }
                return attribute
            }
            let names = attributes.map { $0.attributeName.trimmedDescription }
            let isObjCCompatible = modifiers.contains("dynamic") || names.contains("objc")
            if names.contains("PTIgnored") {
                if names.contains(where: { $0.hasPrefix("PT") && $0 != "PTIgnored" }) {
                    throw MacroExpansionErrorMessage("@PTIgnored cannot be combined with another PTModel field annotation")
                }
                continue
            }
            let wireKey = attributes.first(where: { $0.attributeName.trimmedDescription == "PTKey" })
                .flatMap(firstStringArgument) ?? codingKeys[name] ?? name
            let path = attributes.first(where: { $0.attributeName.trimmedDescription == "PTPath" })
                .flatMap(firstStringArgument)
            let defaultAttribute = attributes.first(where: { $0.attributeName.trimmedDescription == "PTDefault" })
            let defaultExpression = defaultAttribute.flatMap(argumentSource)
                ?? (defaultAttribute == nil ? nil : binding.initializer?.value.trimmedDescription)
            let required = names.contains("PTRequired")
            let flattened = names.contains("PTFlat")
            if flattened && path != nil {
                throw MacroExpansionErrorMessage("@PTFlat and @PTPath cannot be combined")
            }
            if required && defaultAttribute != nil {
                throw MacroExpansionErrorMessage("@PTRequired cannot be combined with @PTDefault")
            }
            if defaultAttribute != nil && defaultExpression == nil && !typeName.hasSuffix("?") {
                throw MacroExpansionErrorMessage("@PTDefault requires an argument or a property initializer for non-optional fields")
            }
            result.append(FieldInfo(name: name,
                                    typeName: typeName,
                                    wireKey: wireKey,
                                    path: path,
                                    defaultExpression: defaultExpression,
                                    isMutable: variable.bindingSpecifier.text == "var",
                                    required: required,
                                    flattened: flattened,
                                    lossy: names.contains("PTLossy"),
                                    stringified: names.contains("PTStringified"),
                                    annotations: names.filter { $0.hasPrefix("PT") },
                                    encoding: required ? ".required" : ".inherit",
                                    missing: defaultAttribute != nil ? ".useDefault" : ".useDefault",
                                    null: defaultAttribute != nil ? ".useDefault" : ".useNil",
                                    invalid: names.contains("PTLossy") ? ".useNil" : ".error",
                                    isObjCCompatible: isObjCCompatible))
        }
        return result
    }

    private static func inferredTypeName(from expression: ExprSyntax?) -> String? {
        guard let expression else { return nil }
        let value = expression.trimmedDescription
        if value == "true" || value == "false" { return "Bool" }
        if value.hasPrefix("\"") && value.hasSuffix("\"") { return "String" }
        if value.contains(".") && Double(value) != nil { return "Double" }
        if Int(value) != nil { return "Int" }
        return nil
    }

    private static func codingKeyMap(from declaration: some DeclGroupSyntax) -> [String: String] {
        var result: [String: String] = [:]
        let source = declaration.memberBlock.description
        for line in source.split(whereSeparator: \.isNewline) {
            let text = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard text.hasPrefix("case "),
                  let equals = text.firstIndex(of: "="),
                  let firstQuote = text[equals...].firstIndex(of: "\""),
                  let lastQuote = text[...].lastIndex(of: "\""),
                  firstQuote < lastQuote else { continue }
            let property = text.dropFirst(5).prefix { $0 != " " && $0 != "=" && $0 != "," }
            guard !property.isEmpty else { continue }
            let valueStart = text.index(after: firstQuote)
            result[String(property)] = String(text[valueStart..<lastQuote])
        }
        return result
    }

    private static func firstStringArgument(_ attribute: AttributeSyntax) -> String? {
        let source = attribute.arguments?.description ?? ""
        guard let firstQuote = source.firstIndex(of: "\""),
              let lastQuote = source.lastIndex(of: "\""),
              firstQuote < lastQuote else { return nil }
        let value = source[source.index(after: firstQuote)..<lastQuote]
        return String(value)
    }

    private static func argumentSource(_ attribute: AttributeSyntax) -> String? {
        let source = attribute.arguments?.description.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        guard !source.isEmpty else { return nil }
        if source.first == "(" && source.last == ")" {
            let start = source.index(after: source.startIndex)
            let end = source.index(before: source.endIndex)
            let value = source[start..<end].trimmingCharacters(in: .whitespacesAndNewlines)
            return value.isEmpty ? nil : String(value)
        }
        return source
    }

    static func escaped(_ value: String) -> String {
        value.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    static func accessPrefix(from declaration: some DeclGroupSyntax) -> String {
        let modifiers: [String]
        if let declaration = declaration.as(StructDeclSyntax.self) {
            modifiers = declaration.modifiers.map(\.name.text)
        } else if let declaration = declaration.as(ClassDeclSyntax.self) {
            modifiers = declaration.modifiers.map(\.name.text)
        } else {
            modifiers = []
        }
        if modifiers.contains("open") { return "open " }
        return modifiers.contains("public") ? "public " : ""
    }

    static func schemaMember(typeName: String,
                             fields: [FieldInfo],
                             supportsDirectConstruction: Bool,
                             superclassName: String? = nil,
                             isClass: Bool = false,
                             accessPrefix: String = "") -> DeclSyntax {
        let decodeFields = fields.map {
            let decodeKeys = $0.wireKey == $0.name
                ? "[\"\(escaped($0.name))\"]"
                : "[\"\(escaped($0.wireKey))\", \"\(escaped($0.name))\"]"
            let path = $0.path.map { "try? PTJSONPath.parse(\"\(escaped($0))\")" } ?? "nil"
            let annotations = "[" + $0.annotations.map { "\"\(escaped($0))\"" }.joined(separator: ", ") + "]"
            let defaultExpression = $0.defaultExpression.map { "\"\(escaped($0))\"" } ?? "nil"
            return "PTModelFieldDescriptor(name: \"\(escaped($0.name))\", mapping: PTModelKeyMapping(decodeKeys: \(decodeKeys), encodeKey: \"\(escaped($0.wireKey))\"), encoding: \($0.encoding), missing: \($0.missing), null: \($0.null), invalid: \($0.invalid), required: \($0.required), flattened: \($0.flattened), path: \(path), annotations: Set(\(annotations)), defaultExpression: \(defaultExpression))"
        }.joined(separator: ", ")
        let ownFieldDeclarations = "[\(decodeFields)]"
        // English: Structs can use their memberwise initializer for the direct scanner path; classes keep the Codable fallback.
        // Español: Las estructuras pueden usar su inicializador memberwise para el scanner directo; las clases conservan el fallback Codable.
        // 中文：结构体可以使用成员初始化器接入直接 Scanner，类继续使用 Codable 回退，避免猜测构造器签名。
        let directDecodeBody = fields.map { field in
            let source = "directInput[\"\(escaped(field.wireKey))\"] ?? directInput[\"\(escaped(field.name))\"]"
            let isOptional = field.typeName.hasSuffix("?")
            let decodeTypeName = isOptional
                ? String(field.typeName.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
                : field.typeName
            let decodedValue: String
            if field.stringified {
                decodedValue = "try PTModelFoundationCodec.decodeStringified(\(decodeTypeName).self, from: raw, decoder: decoder)"
            } else if field.lossy,
                      let collection = lossyCollectionExpression(for: decodeTypeName) {
                decodedValue = "try \(collection)"
            } else if field.required || !isOptional {
                decodedValue = "try decoder.decode(\(decodeTypeName).self, from: raw)"
            } else {
                decodedValue = "try decoder.decodeOptional(\(decodeTypeName).self, from: raw)"
            }
            if let defaultExpression = field.defaultExpression {
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(decodedValue) } else { \(defaultExpression) }"
            }
            if field.required || !isOptional {
                let missingValue = field.lossy && lossyCollectionExpression(for: decodeTypeName) != nil
                    ? "try decoder.decode(\(decodeTypeName).self, from: PTJSONValue.array([]))"
                    : "try decoder.decode(\(decodeTypeName).self, from: PTJSONValue.null)"
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(decodedValue) } else { \(missingValue) }"
            }
            return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(decodedValue) } else { nil }"
        }.joined(separator: "\n            ")
        let directDecodeArguments = fields.map { "\($0.name): \($0.name)" }.joined(separator: ", ")
        let directAssignments = fields.map { "model.\($0.name) = \($0.name)" }.joined(separator: "\n            ")
        let inheritedDirectDecode = superclassName.map {
            "try _ = \($0).ptApplyDirectFields(fields, to: model, using: decoder)"
        } ?? ""
        let inheritedDirectSliceDecode = superclassName.map {
            "try _ = \($0).ptApplyDirectFields(rawFields, to: model, using: decoder)"
        } ?? ""
        let directDecode: String
        if supportsDirectConstruction && isClass {
            directDecode = """

        \(accessPrefix)static func ptDirectDecode(_ fields: [String: PTJSONValue], using decoder: PTModelDecoder) throws -> \(typeName)? {
            let ownFields: [PTModelFieldDescriptor] = \(ownFieldDeclarations)
            let annotated = try PTModelSchemaSupport.applyingAnnotations(to: .object(fields),
                                                                          fields: ownFields,
                                                                          modelType: \(typeName).self,
                                                                          phase: .decode,
                                                                          keyPolicy: decoder.keyPolicy)
            guard case .object(let directInput) = annotated else { throw PTModelError.rootIsNotObject }
            let model = \(typeName)()
            \(inheritedDirectDecode)
            \(directDecodeBody)
            \(directAssignments)
            return model
        }
        """
        } else if supportsDirectConstruction {
            directDecode = """

        \(accessPrefix)static func ptDirectDecode(_ fields: [String: PTJSONValue], using decoder: PTModelDecoder) throws -> \(typeName)? {
            let ownFields: [PTModelFieldDescriptor] = \(ownFieldDeclarations)
            let annotated = try PTModelSchemaSupport.applyingAnnotations(to: .object(fields),
                                                                          fields: ownFields,
                                                                          modelType: \(typeName).self,
                                                                          phase: .decode,
                                                                          keyPolicy: decoder.keyPolicy)
            guard case .object(let directInput) = annotated else { throw PTModelError.rootIsNotObject }
            \(directDecodeBody)
            return \(typeName)(\(directDecodeArguments))
        }
        """
        } else {
            directDecode = ""
        }
        let directSliceDecodeBody = fields.map { field in
            let source = "rawFields[\"\(escaped(field.wireKey))\"] ?? rawFields[\"\(escaped(field.name))\"]"
            let isOptional = field.typeName.hasSuffix("?")
            let decodeTypeName = isOptional
                ? String(field.typeName.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
                : field.typeName
            let decodedValue: String
            if field.stringified {
                decodedValue = "try PTModelFoundationCodec.decodeStringified(\(decodeTypeName).self, from: .string(try decoder.decodeRaw(String.self, from: raw)), decoder: decoder)"
            } else if field.lossy,
                      let collection = lossyRawCollectionExpression(for: decodeTypeName) {
                decodedValue = "try \(collection)"
            } else if field.required || !isOptional {
                decodedValue = "try decoder.decodeRaw(\(decodeTypeName).self, from: raw)"
            } else {
                decodedValue = "try decoder.decodeRaw(\(decodeTypeName).self, from: raw)"
            }
            if let defaultExpression = field.defaultExpression {
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(decodedValue) } else { \(defaultExpression) }"
            }
            if field.required || !isOptional {
                let missingValue = field.lossy && lossyCollectionExpression(for: decodeTypeName) != nil
                    ? "try decoder.decode(\(decodeTypeName).self, from: PTJSONValue.array([]))"
                    : "try decoder.decode(\(decodeTypeName).self, from: PTJSONValue.null)"
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(decodedValue) } else { \(missingValue) }"
            }
            return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(decodedValue) } else { nil }"
        }.joined(separator: "\n            ")
        let directSliceDecode: String
        if supportsDirectConstruction && isClass {
            directSliceDecode = """

        \(accessPrefix)static func ptDirectDecodeSlices(_ rawFields: [String: Data], using decoder: PTModelDecoder) throws -> \(typeName)? {
            let model = \(typeName)()
            \(inheritedDirectSliceDecode)
            \(directSliceDecodeBody)
            \(directAssignments)
            return model
        }
        """
        } else if supportsDirectConstruction {
            directSliceDecode = """

        \(accessPrefix)static func ptDirectDecodeSlices(_ rawFields: [String: Data], using decoder: PTModelDecoder) throws -> \(typeName)? {
            \(directSliceDecodeBody)
            return \(typeName)(\(directDecodeArguments))
        }
        """
        } else {
            directSliceDecode = ""
        }
        let schemaOnlyAnnotations = ["PTPolymorphic", "PTExtras"]
        let hasSchemaOnlyAnnotations = fields.contains {
            $0.isObjCCompatible || $0.annotations.contains(where: schemaOnlyAnnotations.contains)
        }
        let directPathFlag = supportsDirectConstruction && !hasSchemaOnlyAnnotations
            ? "\(accessPrefix)static var ptUsesDirectPath: Bool { true }"
            : "\(accessPrefix)static var ptUsesDirectPath: Bool { false }"
        let parentFields = superclassName.map { "\($0).ptSchema.metadata.fields" } ?? "[]"
        let mergedFields = "PTModelSchemaSupport.mergedFields(parent: \(parentFields), own: ownFields)"
        let ownEncodedValues = fields.enumerated().map {
            let value = $0.element.stringified
                ? "encoder.optionalJSONValue(PTStringifiedValue(model.\($0.element.name)))"
                : "encoder.optionalJSONValue(model.\($0.element.name))"
            let annotated = "try (\(value)).map { try PTModelSchemaSupport.applyingAnnotation(to: $0, field: ownFields[\($0.offset)], modelType: \(typeName).self, phase: .encode) }"
            return "(ownFields[\($0.offset)], \(annotated))"
        }.joined(separator: ",\n                                                  ")
        let inheritedEncodedValues = superclassName.map { "(try \($0).ptDirectFieldValues(model, using: encoder)) ?? []" } ?? "[]"
        let encodedValues = "\(inheritedEncodedValues) + [\(ownEncodedValues)]"
        let directApply = (isClass && supportsDirectConstruction) ? """

        \(accessPrefix)static func ptApplyDirectFields(_ fields: [String: PTJSONValue], to model: \(typeName), using decoder: PTModelDecoder) throws -> \(typeName) {
            \(directDecodeBody)
            \(directAssignments)
            return model
        }
        """ : ""
        let directApplySlices = (isClass && supportsDirectConstruction) ? """

        \(accessPrefix)static func ptApplyDirectFields(_ rawFields: [String: Data], to model: \(typeName), using decoder: PTModelDecoder) throws -> \(typeName) {
            \(directSliceDecodeBody)
            \(directAssignments)
            return model
        }
        """ : ""
        return DeclSyntax(stringLiteral: """
        \(directPathFlag)

        \(accessPrefix)static var ptSchemaPrecedence: PTStaticSchemaPrecedence { .staticBeforeCodable }

        \(accessPrefix)static var ptSchema: PTModelSchema<\(typeName)> {
            let ownFields: [PTModelFieldDescriptor] = \(ownFieldDeclarations)
            let merged = \(mergedFields)
            let fields = merged.fields
            return PTModelSchema<\(typeName)>(name: "\(escaped(typeName))",
                                       fields: fields,
                                       conflicts: merged.conflicts,
                                       decode: { value, decoder in
                                           let normalized = PTModelSchemaSupport.normalizedInput(value,
                                                                                                  fields: fields,
                                                                                                  keyPolicy: decoder.keyPolicy)
                                           let annotated = try PTModelSchemaSupport.applyingAnnotations(to: normalized,
                                                                                                           fields: fields,
                                                                                                           modelType: \(typeName).self,
                                                                                                           phase: .decode,
                                                                                                           keyPolicy: decoder.keyPolicy)
                                           return try decoder.decode(\(typeName).self, from: annotated)
                                       },
                                       encode: { model, encoder in
                                           let encoded = try encoder.object(fields: \(encodedValues))
                                           let annotated = try PTModelSchemaSupport.applyingAnnotations(to: encoded,
                                                                                                           fields: fields,
                                                                                                           modelType: \(typeName).self,
                                                                                                           phase: .encode,
                                                                                                           keyPolicy: encoder.keyPolicy)
                                           return try PTModelSchemaSupport.encodedOutput(annotated,
                                                                                          fields: fields,
                                                                                          using: encoder)
                                       })
        }

        \(accessPrefix)static func ptDirectFieldValues(_ model: \(typeName), using encoder: PTModelEncoder) throws -> [(PTModelFieldDescriptor, PTJSONValue?)]? {
            let ownFields: [PTModelFieldDescriptor] = \(ownFieldDeclarations)
            return \(encodedValues)
        }
        \(directDecode)
        \(directSliceDecode)
        \(directApply)
        \(directApplySlices)
        """)
    }

    // English: Classes use overridable, type-erased schema members because a non-final class cannot conform to a Self-typed schema property.
    // Español: Las clases usan miembros de esquema sobrescribibles y borrados por tipo porque una clase no final no puede conformar a una propiedad tipada con Self.
    // 中文：非 final 类不能满足带 Self 的 Schema 属性，因此类模型使用可覆盖的类型擦除成员。
    static func classSchemaMember(typeName: String,
                                  fields: [FieldInfo],
                                  superclassName: String?,
                                  accessPrefix: String,
                                  supportsDirectConstruction: Bool) -> DeclSyntax {
        let decodeFields = fields.map {
            let decodeKeys = $0.wireKey == $0.name
                ? "[\"\(escaped($0.name))\"]"
                : "[\"\(escaped($0.wireKey))\", \"\(escaped($0.name))\"]"
            let path = $0.path.map { "try? PTJSONPath.parse(\"\(escaped($0))\")" } ?? "nil"
            let annotations = "[" + $0.annotations.map { "\"\(escaped($0))\"" }.joined(separator: ", ") + "]"
            let defaultExpression = $0.defaultExpression.map { "\"\(escaped($0))\"" } ?? "nil"
            return "PTModelFieldDescriptor(name: \"\(escaped($0.name))\", mapping: PTModelKeyMapping(decodeKeys: \(decodeKeys), encodeKey: \"\(escaped($0.wireKey))\"), encoding: \($0.encoding), missing: \($0.missing), null: \($0.null), invalid: \($0.invalid), required: \($0.required), flattened: \($0.flattened), path: \(path), annotations: Set(\(annotations)), defaultExpression: \(defaultExpression))"
        }.joined(separator: ", ")
        let ownFields = "[\(decodeFields)]"
        let parentFields = superclassName.map { "\($0).ptClassSchemaMetadata.fields" } ?? "[]"
        let mergedFields = "PTModelSchemaSupport.mergedFields(parent: \(parentFields), own: ownFields)"
        let overridePrefix = superclassName == nil ? "" : "override "
        let classPrefix = "\(accessPrefix)\(overridePrefix)class"
        let directBody = fields.map { field in
            let source = "fields[\"\(escaped(field.wireKey))\"] ?? fields[\"\(escaped(field.name))\"]"
            let optional = field.typeName.hasSuffix("?")
            let typeName = optional ? String(field.typeName.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines) : field.typeName
            let value: String
            if field.stringified {
                value = "try PTModelFoundationCodec.decodeStringified(\(typeName).self, from: raw, decoder: decoder)"
            } else if field.lossy, let collection = lossyCollectionExpression(for: typeName) {
                value = "try \(collection)"
            } else if optional {
                value = "try decoder.decodeOptional(\(typeName).self, from: raw)"
            } else {
                value = "try decoder.decode(\(typeName).self, from: raw)"
            }
            if let defaultExpression = field.defaultExpression {
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(value) } else { \(defaultExpression) }"
            }
            if optional {
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(value) } else { nil }"
            }
            return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(value) } else { try decoder.decode(\(typeName).self, from: PTJSONValue.null) }"
        }.joined(separator: "\n            ")
        let sliceBody = fields.map { field in
            let source = "rawFields[\"\(escaped(field.wireKey))\"] ?? rawFields[\"\(escaped(field.name))\"]"
            let optional = field.typeName.hasSuffix("?")
            let typeName = optional ? String(field.typeName.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines) : field.typeName
            let value: String
            if field.stringified {
                value = "try PTModelFoundationCodec.decodeStringified(\(typeName).self, from: .string(try decoder.decodeRaw(String.self, from: raw)), decoder: decoder)"
            } else if field.lossy, let collection = lossyRawCollectionExpression(for: typeName) {
                value = "try \(collection)"
            } else {
                value = "try decoder.decodeRaw(\(typeName).self, from: raw)"
            }
            if let defaultExpression = field.defaultExpression {
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(value) } else { \(defaultExpression) }"
            }
            if optional {
                return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(value) } else { nil }"
            }
            return "let \(field.name): \(field.typeName) = if let raw = \(source) { \(value) } else { try decoder.decode(\(typeName).self, from: PTJSONValue.null) }"
        }.joined(separator: "\n            ")
        let assignments = fields.map { "model.\($0.name) = \($0.name)" }.joined(separator: "\n            ")
        let parentApply = superclassName.map { "try _ = \($0).ptClassApplyDirectFields(fields, to: model, using: decoder)" } ?? ""
        let parentApplySlices = superclassName.map { "try _ = \($0).ptClassApplyDirectFields(rawFields, to: model, using: decoder)" } ?? ""
        let parentValues = superclassName.map { "((try \($0).ptClassDirectFieldValues(model, using: encoder)) ?? [])" } ?? "[]"
        let values = fields.enumerated().map { index, field in
            let value = field.stringified
                ? "try encoder.optionalJSONValue(PTStringifiedValue(model.\(field.name)))"
                : "try encoder.optionalJSONValue(model.\(field.name))"
            return "(ownFields[\(index)], \(value))"
        }.joined(separator: ", ")
        let schemaOnlyAnnotations = ["PTTransform", "PTValidate", "PTPolymorphic", "PTExtras"]
        let hasSchemaOnlyAnnotations = fields.contains {
            $0.isObjCCompatible || $0.annotations.contains(where: schemaOnlyAnnotations.contains)
        }
        let directFlag = supportsDirectConstruction &&
            !hasSchemaOnlyAnnotations &&
            fields.allSatisfy { $0.isMutable }
        let directPrefix = directFlag ? "true" : "false"
        let directDecodeMethods: String
        if directFlag {
            directDecodeMethods = """

        \(classPrefix) func ptClassDirectDecode(_ fields: [String: PTJSONValue], using decoder: PTModelDecoder) throws -> AnyObject? {
            let model = \(typeName)()
            \(parentApply)
            \(directBody)
            \(assignments)
            return model
        }

        \(classPrefix) func ptClassDirectDecodeSlices(_ rawFields: [String: Data], using decoder: PTModelDecoder) throws -> AnyObject? {
            let model = \(typeName)()
            \(parentApplySlices)
            \(sliceBody)
            \(assignments)
            return model
        }

        \(classPrefix) func ptClassApplyDirectFields(_ fields: [String: PTJSONValue], to rawModel: AnyObject, using decoder: PTModelDecoder) throws -> AnyObject {
            guard let model = rawModel as? \(typeName) else {
                throw PTModelError.underlying("Generated class schema received an unexpected model type")
            }
            \(parentApply)
            \(directBody)
            \(assignments)
            return model
        }

        \(classPrefix) func ptClassApplyDirectFields(_ rawFields: [String: Data], to rawModel: AnyObject, using decoder: PTModelDecoder) throws -> AnyObject {
            guard let model = rawModel as? \(typeName) else {
                throw PTModelError.underlying("Generated class schema received an unexpected model type")
            }
            \(parentApplySlices)
            \(sliceBody)
            \(assignments)
            return model
        }
        """
        } else {
            directDecodeMethods = """

        \(classPrefix) func ptClassDirectDecode(_ fields: [String: PTJSONValue], using decoder: PTModelDecoder) throws -> AnyObject? {
            nil
        }

        \(classPrefix) func ptClassDirectDecodeSlices(_ rawFields: [String: Data], using decoder: PTModelDecoder) throws -> AnyObject? {
            nil
        }

        \(classPrefix) func ptClassApplyDirectFields(_ fields: [String: PTJSONValue], to rawModel: AnyObject, using decoder: PTModelDecoder) throws -> AnyObject {
            rawModel
        }

        \(classPrefix) func ptClassApplyDirectFields(_ rawFields: [String: Data], to rawModel: AnyObject, using decoder: PTModelDecoder) throws -> AnyObject {
            rawModel
        }
        """
        }
        return DeclSyntax(stringLiteral: """
        \(classPrefix) var ptClassSchemaMetadata: PTModelSchemaMetadata {
            let ownFields: [PTModelFieldDescriptor] = \(ownFields)
            let merged = \(mergedFields)
            return PTModelSchemaMetadata(name: "\(escaped(typeName))", fields: merged.fields, conflicts: merged.conflicts)
        }

        \(classPrefix) var ptClassSchemaPrecedence: PTStaticSchemaPrecedence { .staticBeforeCodable }
        \(classPrefix) var ptClassUsesDirectPath: Bool { \(directPrefix) }

        \(classPrefix) func ptClassDecode(_ value: PTJSONValue, using decoder: PTModelDecoder) throws -> AnyObject {
            let fields = Self.ptClassSchemaMetadata.fields
            let normalized = PTModelSchemaSupport.normalizedInput(value,
                                                                   fields: fields,
                                                                   keyPolicy: decoder.keyPolicy)
            let annotated = try PTModelSchemaSupport.applyingAnnotations(to: normalized,
                                                                           fields: fields,
                                                                           modelType: \(typeName).self,
                                                                           phase: .decode,
                                                                           keyPolicy: decoder.keyPolicy)
            return try decoder.decode(\(typeName).self, from: annotated)
        }

        \(classPrefix) func ptClassEncode(_ rawModel: AnyObject, using encoder: PTModelEncoder) throws -> PTJSONValue {
            guard let model = rawModel as? \(typeName) else {
                throw PTModelError.underlying("Generated class schema received an unexpected model type")
            }
            let ownFields: [PTModelFieldDescriptor] = \(ownFields)
            let encoded = try encoder.object(fields: \(parentValues) + [\(values)])
            let annotated = try PTModelSchemaSupport.applyingAnnotations(to: encoded,
                                                                           fields: Self.ptClassSchemaMetadata.fields,
                                                                           modelType: \(typeName).self,
                                                                           phase: .encode,
                                                                           keyPolicy: encoder.keyPolicy)
            return try PTModelSchemaSupport.encodedOutput(annotated,
                                                          fields: Self.ptClassSchemaMetadata.fields,
                                                          using: encoder)
        }

        \(directDecodeMethods)

        \(classPrefix) func ptClassDirectFieldValues(_ rawModel: AnyObject, using encoder: PTModelEncoder) throws -> [(PTModelFieldDescriptor, PTJSONValue?)]? {
            guard let model = rawModel as? \(typeName) else {
                throw PTModelError.underlying("Generated class schema received an unexpected model type")
            }
            let ownFields: [PTModelFieldDescriptor] = \(ownFields)
            return \(parentValues) + [\(values)]
        }
        """)
    }

    private static func lossyCollectionExpression(for typeName: String) -> String? {
        guard typeName.hasPrefix("[") && typeName.hasSuffix("]") else { return nil }
        let inner = String(typeName.dropFirst().dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !inner.isEmpty else { return nil }
        if inner.hasSuffix("?") {
            let element = String(inner.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
            return "decoder.decodeOptionalArray(\(element).self, from: raw, strategy: .preserveIndexAsNil)"
        }
        return "decoder.decodeArray(\(inner).self, from: raw, strategy: .skipInvalid)"
    }

    // English: Use Data slices for generated lossy fields so the direct path stays tree-free for valid elements.
    // Español: Usa slices Data para campos lossless generados y mantiene la ruta directa sin árbol para elementos válidos.
    // 中文：生成的 Lossy 字段使用 Data 切片，让直接路径对有效元素保持无树解码。
    private static func lossyRawCollectionExpression(for typeName: String) -> String? {
        guard typeName.hasPrefix("[") && typeName.hasSuffix("]") else { return nil }
        let inner = String(typeName.dropFirst().dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !inner.isEmpty else { return nil }
        if inner.hasSuffix("?") {
            let element = String(inner.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
            return "decoder.decodeRawOptionalArray(\(element).self, from: raw, strategy: .preserveIndexAsNil)"
        }
        return "decoder.decodeRawArray(\(inner).self, from: raw, strategy: .skipInvalid)"
    }
}

public struct PTModelMacro: MemberMacro, ExtensionMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let typeName = PTMacroSourceBuilder.typeName(from: declaration) else {
            throw MacroExpansionErrorMessage("@PTModel can only be attached to a struct or class")
        }
        try PTMacroSourceBuilder.validateTypeBoundary(declaration)
        let fields = try PTMacroSourceBuilder.fields(from: declaration)
        let isClass = declaration.as(ClassDeclSyntax.self) != nil
        let supportsDirectConstruction = isClass
            ? PTMacroSourceBuilder.hasDirectClassInitializer(declaration, fields: fields)
            : true
        if isClass {
            return [PTMacroSourceBuilder.classSchemaMember(typeName: typeName,
                                                           fields: fields,
                                                           superclassName: nil,
                                                           accessPrefix: PTMacroSourceBuilder.accessPrefix(from: declaration),
                                                           supportsDirectConstruction: PTMacroSourceBuilder.hasDirectClassInitializer(declaration,
                                                                                                                                            fields: fields))]
        }
        return [PTMacroSourceBuilder.schemaMember(typeName: typeName,
                                                  fields: fields,
                                                  supportsDirectConstruction: supportsDirectConstruction,
                                                  superclassName: nil,
                                                  isClass: false,
                                                  accessPrefix: PTMacroSourceBuilder.accessPrefix(from: declaration))]
    }

    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [ExtensionDeclSyntax] {
        guard PTMacroSourceBuilder.typeName(from: declaration) != nil else {
            throw MacroExpansionErrorMessage("@PTModel can only be attached to a struct or class")
        }
        if declaration.as(ClassDeclSyntax.self) != nil {
            throw MacroExpansionErrorMessage("@PTModel is for structs; use @PTSubclass for Codable classes")
        }
        return [try ExtensionDeclSyntax("extension \(type.trimmed): PTStaticModel {}")]
    }
}

public struct PTSubclassMacro: MemberMacro, ExtensionMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let typeName = PTMacroSourceBuilder.typeName(from: declaration) else {
            throw MacroExpansionErrorMessage("@PTSubclass can only be attached to a class")
        }
        try PTMacroSourceBuilder.validateTypeBoundary(declaration)
        let fields = try PTMacroSourceBuilder.fields(from: declaration)
        let superclassName = PTMacroSourceBuilder.superclassName(from: declaration)
        let supportsDirectConstruction = PTMacroSourceBuilder.hasDirectClassInitializer(declaration, fields: fields)
        return [PTMacroSourceBuilder.classSchemaMember(typeName: typeName,
                                                       fields: fields,
                                                       superclassName: superclassName,
                                                       accessPrefix: PTMacroSourceBuilder.accessPrefix(from: declaration),
                                                       supportsDirectConstruction: supportsDirectConstruction)]
    }

    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [ExtensionDeclSyntax] {
        guard declaration.is(ClassDeclSyntax.self) else {
            throw MacroExpansionErrorMessage("@PTSubclass can only be attached to a class")
        }
        return []
    }
}

public struct PTFieldAnnotationMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        // English: Marker annotations only feed the enclosing PTModel macro; they emit no runtime declarations.
        // Español: Las anotaciones marcador solo alimentan a PTModel y no emiten declaraciones de runtime.
        // 中文：标记注解只供 PTModel 宏读取，不生成运行时声明。
        []
    }
}

@main
struct PToolsModelMacrosPlugin: CompilerPlugin {
    let providingMacros: [Macro.Type] = [PTModelMacro.self, PTSubclassMacro.self, PTFieldAnnotationMacro.self]
}
